import './globals.css'

export const metadata = {
  title: 'BookShelf - Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}
